# Generated by Django 2.2.3 on 2019-07-12 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellgood', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['seller']},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='minimum_value',
            new_name='minimum_amount',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='value',
            new_name='amount',
        ),
    ]
